version: '2'
services:
  web:
    build: .
    environment:
    - MONGODB_APP_HOST=mongodemo    
    ports:
     - "8080:80"
    depends_on:
     - "mongodemo"
    entrypoint: ./wait-for-it.sh mongodemo:27017
  mongodemo:
    image: mongo:latest

